name: 'Generate Fortify tool descriptors'
description: 'Generate Fortify tool descriptors'
author: 'Fortify'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token used to perform GitHub operations'
    required: true
  toolName:
    description: 'The tool name for which to generate tool definitions.'
    required: true
  toolRepo:
    description: 'The GitHub repository for which to generate tool definitions. Required unless tool_urls is specified.'
    required: false
  toolUrls:
    description: 'JSON string specifying tool versions & URLs for which to generate tool definitions, in the format {"<version>": "<url>", ...}. Required unless tool_repo is specified.'
    required: false
  tagRegex:
    description: 'Optional regular expressions to define what release tags to include'
    required: false
  tagMappings:
    description: 'Optional JSON string specifying release tag regex to replacement tag, in the format {"<tag-regex>": "<replacement>", ...}. The replacement can use $<ref> to reference indexed or named capturing groups.'
    required: false
  assetRegex:
    description: 'Optional regular expression to define what releases assets to include'
    required: false
  signKey:
    description: 'Non-wrapped base64-encoded RSA signing key, usually provided through GitHub secret, generated using `base64 -w0 << private-key.pem`'
    required: true
  signPassphrase:
    description: 'Passphrase for the RSA signing key provided throgh sign_key, usually provided through GitHub secret'
    required: true
  semver:
    description: 'Define what semantic versions to include; can be none (default, only full versions), minor (only minor and full versions) or major (major, minor and full versions)'
    default: 'none'
    required: false
  binaryPlatforms:
    description: 'JSON string specifying artifact lowercase download URL regex to artifact platform mappings {"<regex>": "<platform>",..}'
    required: true
runs:
  using: node20
  main: 'dist/index.js'
branding:
  icon: 'shield'
  color: 'blue'

